### ISSUE TITLE
Roadmap/wishlist

### ISSUE THREAD

**Issue by bartvm** [alexandresablayrolles/nmt#1]
Just putting this here for reference:

- [ ] Support for batches of variable length (i.e. masks)
  - [ ] MaskedSequencer
  - [ ] MaskedSoftMax
  - [ ] MaskedSequencerCriterion
- [ ] Beam search for sampling
- [ ] Dataset preprocessing and evaluation scripts
- [ ] Multi-GPU support (EASGD, but maybe AdaDelta equivalent)
- [ ] [Scheduled sampling](http://arxiv.org/abs/1506.03099)
- [ ] Softmax sampling
  - [ ] [Montreal approach](http://arxiv.org/abs/1412.2007)
  - [ ] Negative sampling
- [ ] Replacing unknown words in the target with most strongly aligned word
- [ ] Support for bag-of-words and convolutions in the encoder
